# Build APKs for Kiwi Browser Next
name: 'Kiwi: Build and sign release apk'

on:
  workflow_dispatch:
    inputs:
      prepareRelease:
        description: 'Create a draft release in Google Play Store'     
        required: true
        default: 'no'
      announceOnMessengers:
        description: 'Announce new release on Discord and Telegram channels'     
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [arm64]

    steps:
      - name: Initializing build
        run: echo Initializing build for platform ${{ matrix.platform }}

      - name: Updating APT repository
        run: sudo apt-get update

      - name: Installing rclone
        run: sudo -v ; wget https://downloads.rclone.org/v1.63.1/rclone-v1.63.1-linux-amd64.deb && sudo dpkg -i rclone-v1.63.1-linux-amd64.deb

      - name: Installing Python and OpenJDK
        run: sudo apt-get install -y 2to3 python3-minimal python3 dh-python python-is-python3 openjdk-8-jdk-headless ccache jq

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Reclaiming disk space on / by removing .NET framework
        run: sudo rm -rf /usr/share/dotnet

      - name: Checking-out source-code in $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Creating secondary disk folder on /dev/disk/azure/resource-part1 (SSD)
        run: |
          sudo mkdir -p /extended_data
          sudo chown -R runner:docker /extended_data
      
      - name: On SSD - Creating symlink on /dev/disk/azure/root-part1 pointing to /dev/disk/azure/resource-part1
        run: |
          sudo ln -s /extended_data /mnt/secondary_disk
          sudo ln -s /mnt/secondary_disk $GITHUB_WORKSPACE/

      - name: Creating output folder
        run: mkdir -p secondary_disk/out/android_${{ matrix.platform }}

      - name: Generating one-time APK signature key
        run: keytool -genkey -v -keystore keystore.jks -alias dev -keyalg RSA -keysize 2048 -validity 10000 -storepass public_password -keypass public_password -dname "cn=Kiwi Browser (unverified), ou=Actions, o=Kiwi Browser, c=GitHub"

      - name: Copying args.gn to target folder
        run: cat .build/android_arm/args.gn | sed "s#target_cpu = \"arm\"#target_cpu = \"${{ matrix.platform }}\"#" | sed "s#android_default_version_name = \"Git\"#android_default_version_name = \"Git$(date '+%y%m%d')Gen${{ github.run_id }}\"#" > secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Creating rclone config
        run: |
          mkdir -p $HOME/.config/rclone/
          echo '[cache]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.STORAGE_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = storage' >> $HOME/.config/rclone/rclone.conf
          echo 'key_pem = ${{ secrets.STORAGE_KEY }}' >> $HOME/.config/rclone/rclone.conf

      - name: Modifying args.gn (arm64)
        if: matrix.platform == 'arm64'
        run: sed -i "s#android_default_version_code = \"1\"#android_default_version_code = \"$(date '+%y%m%d')2\"#" secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Displaying args.gn
        run: cat secondary_disk/out/android_${{ matrix.platform }}/args.gn

      - name: Checking available disk-space
        run: df -h

      - name: Uploading args.gn
        run: rclone copy --transfers=128 --retries=10 secondary_disk/out/android_${{ matrix.platform }}/args.gn cache:kiwibrowser-next-builds-${{ matrix.platform }}/

      - name: Downloading binary objects cache to $HOME/cache
        run: rclone copy --transfers=128 --retries=10 cache:kiwibrowser-next-builds-${{ matrix.platform }}/ $HOME/kiwibrowser-next-builds-${{ matrix.platform }}

      - name: Transferring build to the standard Kiwi Browser run ID
        run: rclone copy --transfers=128 --retries=10 cache:kiwibrowser-next-builds-${{ matrix.platform }}/ cache:kiwibrowser-builds/${{ github.run_id }}/${{ matrix.platform }}

      - name: Listing files
        run: |
          echo $HOME
          ls -la $HOME/kiwibrowser-next-builds-${{ matrix.platform }}

      - name: Uploading APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ matrix.platform }}
          path: /home/runner/kiwibrowser-next-builds-${{ matrix.platform }}/

  sign_and_upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Installing rclone
        run: curl --http1.1 https://rclone.org/install.sh | sudo bash
    
      - name: Creating rclone config
        run: |
          mkdir -p $HOME/.config/rclone/
          echo '[cache]' > $HOME/.config/rclone/rclone.conf
          echo 'type = sftp' >> $HOME/.config/rclone/rclone.conf
          echo 'host = ${{ secrets.STORAGE_HOST }}' >> $HOME/.config/rclone/rclone.conf
          echo 'user = storage' >> $HOME/.config/rclone/rclone.conf
          echo 'key_pem = ${{ secrets.STORAGE_KEY }}' >> $HOME/.config/rclone/rclone.conf

      - name: Downloading artifact (arm64)
        uses: actions/download-artifact@v4
        with:
          name: apk-arm64
          path: apk-arm64

      - name: Listing files under $HOME
        run: |
          pwd
          echo $HOME
          ls -laR $HOME

      - name: Prepare release notes
        run: |
          cat ./apk-arm64/last_commits.txt > release_notes.txt
          cat <<EOT >> release_notes.txt
          
          This version will replace your currently installed Kiwi Browser (com.kiwibrowser.browser).
          If you have important data, make sure to backup them or save them before upgrading to this version.
          
          This release was automatically generated from GitHub ${{ github.ref }} in run ID ${{ github.run_id }}.
          
          Summary:
            - To install / update Kiwi Browser, use "com.kiwibrowser.browser-arm64-${{ github.run_id }}-github.apk".
          
          Build version:
           - Everytime a change is introduced in Kiwi Browser, a new build version is generated.
          
          Architecture:
            - "-arm64" is compatible with modern devices and offers the best performance.
          EOT

      - name: Creating release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: "kiwibrowser"
          repo: "src.next"
          tag_name: ${{ github.run_id }}
          release_name: Generation ${{ github.run_id }}
          draft: false
          prerelease: true
          body_path: release_notes.txt

      - name: Downloading artifacts from storage
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        run: |
          rclone copy --transfers=128 --retries=100 cache:kiwibrowser-builds/${{ github.run_id }}/arm64/ ./apk-arm64

      - name: Uploading release asset (arm64-signed)
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-arm64/ChromePublic-DevSigned.apk
          asset_name: com.kiwibrowser.browser-arm64-${{ github.run_id }}-github.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Uploading dev asset (arm64-signed)
        if: ${{ github.repository_owner == 'kiwibrowser' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-arm64/ChromePublic-Next-DevSigned.apk
          asset_name: com.kiwibrowser.browser.dev-arm64-${{ github.run_id }}-github.apk
          asset_content_type: application/vnd.android.package-archive
